import { getSimpleDistance, getEmptyRowsAndCols, getDistances } from "./day11"

describe("day 11", () => {
  it("gets the empty rows and columns", () => {
    const example = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`

    expect(getEmptyRowsAndCols(example)).toEqual({
      rows: [3, 7],
      cols: [2, 5, 8],
    })
  })

  it("gets the right distance for the examples", () => {
    const example = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`

    expect(getSimpleDistance(example)).toBe(374)
  })

  it("gets the right distance for expanded space", () => {
    const example = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`

    expect(getDistances(9)(example)).toBe(1030)
    expect(getDistances(99)(example)).toBe(8410)
  })
})
